### PR TITLE
Update GLM to 0.9.9.6 to fix windows compilation with CUDA > 8

### LINKED ISSUE #267: GLM in VS 2019 with CUDA 10.1
Build error for ped navigation model

C:\Code\FLAMEGPU\include\glm\detail/qualifier.hpp(96): error : attributes are not allowed here

### PR DESCRIPTION
**Pull request by ptheywood**
Updates GLM to 0.9.9.6 which should resolve #267.

Needs testing with various OS/compiler/nvcc versions, although it looks promising.

We probably don't need a full OS / CUDA / Compiler matrix testing, but worth doing linux + windows, with recent (major) cuda versions and recent VS versions (as the source of the main issue). 

| OS | CUDA | Compiler | User | Pass/Fail?|
|-----|----------|---------------|-------|------|
| Ubuntu 18.04 | 10.1 | GCC 7.4 | @ptheywood | OK | 
| Ubuntu 18.04 | 10.0 | GCC 7.4 | @ptheywood | OK | 
| Ubuntu 18.04 | 9.2 | GCC 6.5 | @ptheywood | OK |
| Ubuntu 18.04 | 9.0 | GCC 6.5 | @ptheywood | OK |
| Ubuntu 18.04 | 8.0 | GCC 5.5 | @ptheywood | OK |
| Windows 10 | 10.x | VS 2019 | ??? | ??? |
| Windows 10 | 9.x | VS 2019 | ??? | ??? |
| Windows 10 | 10.x | VS 2017 | ??? | ??? |
| Windows 10 | 9.x | VS 2017 | ??? | ??? |
| Windows 10 | 10.x | VS 2015 | ??? | ??? |
| Windows 10 | 9.2 | VS 2015 | @cmoralesmx | OK |
| Windows 10 | 8.0 | VS 2015 | @cmoralesmx | OK ([log](https://gist.github.com/cmoralesmx/2d3d0c3d757e5099a6b7472bd06a519b)) |

### CODE REVIEW

**Comment by ptheywood** [comment]
I've just done a full rebuild with VS 2019 and CUDA 10.1 This succeeded with the latest GLM branch which combined with 2015 support and linux support is good enough for me,  so I'll merge.
