### ISSUE TITLE
GLM in VS 2019 with CUDA 10.1

### ISSUE THREAD

**Issue by mondus** [FLAMEGPU/FLAMEGPU#267]
Build error for ped navigation model

C:\Code\FLAMEGPU\include\glm\detail/qualifier.hpp(96): error : attributes are not allowed here

**Comment by ptheywood** [comment]
GLM and CUDA 10 seems to be the issue, even with VS2015. Upgrading to the latest GLM release doesn't fix the issues (@mozhgan-kch tested this), so likely a VS compiler + nvcc issue which GLM is exposing.
Older CUDA version *may* work with latest GLM, it might not.

**Comment by ptheywood** [comment]
https://github.com/g-truc/glm/issues/819 is a related but not overly helpful issue.

**Comment by ptheywood** [comment]
Downgrading GLM to 0.9.9.0 (the version from FLAME GPU 1.5.0 release) seems to work with VS 2015 and CUDA 9.2 (as included in the 1.5.0 release). Not yet tested with CUDA 10.0 or newer. 

The upgrade was made in 42f84e0, to fix GLM bug(s) regarding double precision equality tests.

**Comment by ptheywood** [comment]
@mozhgan-kch has confirmed that 0.9.9.0 works with VS 2019 and CUDA 10.1

Options are 
+ downgrade GLM (re introducing double precision vector bug(s)) 
+ fix and upgrade GLM (ideally contributing upstream). 

It might also be worth checking the latest development version of GLM (i.e. master branch rather than the 0.9.9.5 release)

**Comment by cmoralesmx** [comment]
I recently attempted compiling my model in windows using VS2015 and CUDA 8.0 but got the same errors "attributes are not allowed here". BTW, my model is based on your current master. So, I downgraded to 0.9.9.0 from your v1.5 release and compilation was successful. However, I also tested upgrading to GLM 0.9.9.6 and the errors were not present. I did not test the rest of the examples though.

**Comment by ptheywood** [comment]
It's worth noting that 0.9.9.6 appears to remove support for Cuda 8 and below

https://github.com/g-truc/glm/commit/943529eef619d3448bab918fb678e89568632fb0

**Comment by cmoralesmx** [comment]
I can report the examples are compiling correctly using VS2015, CUDA 8.0 and glm 0.9.9.6.  
Here is a [gist](https://gist.github.com/cmoralesmx/2d3d0c3d757e5099a6b7472bd06a519b) with the compile log for your reference.  
Also tested compiling the examples with glm 0.9.9.6 and CUDA v9.2 in VS2015 with success.
The minimum CUDA version they are supporting with this release seems to be v8.0
